### ISSUE TITLE
Project idea

### ISSUE THREAD

**Issue by suciularisa** [suciularisa/hackaton2021#1]

**Comment by andreealungu238** [comment]
-> harta cu locuri de reciclat 
-> aplicatie mascata de SOS
-> aplicatie care traducere din text in limbajul semnelor

**Comment by draguleee** [comment]
Idee de proiect: un Hub care ofera diverse servicii in functie de locatia in care se afla utilizatorul:
- Servicii precum: telefonie si internet, gaz, curent electric
- Servicii locale, precum: instalatii, reparari, mecanic
- Diverse magazine locale
- Atractii turistice

**Comment by VandiciAlexandru** [comment]
Final Decision: The Hub
